version: '3'

services:
  app:
    container_name: Eccomerse_FRONT
    build: .
    restart: unless-stopped
    ports:
      - 4200:4200
    volumes:
      - ./dist:/usr/src/app/dist
      - .:/usr/src/app
